# Generated by Django 3.0 on 2020-05-05 22:41

from django.db import migrations, models
import django_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image1', django_fields.fields.DefaultStaticImageField(blank=True, upload_to='')),
                ('image2', django_fields.fields.DefaultStaticImageField(blank=True, upload_to='')),
                ('image3', django_fields.fields.DefaultStaticImageField(blank=True, upload_to='')),
                ('image4', django_fields.fields.DefaultStaticImageField(blank=True, upload_to='')),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
